In [1]:
import tensorflow as tf

In [2]:
sess = tf.Session()
hello = tf.constant("Hello, TensorFlow!")
print(sess.run(hello))

NameError: name 'th' is not defined

In [3]:
sess = tf.Session()
hello = tf.constant("Hello, TensorFlow!")
print(sess.run(hello))

b'Hello, TensorFlow!'


In [4]:
a = tf.constant(111)
b = tf.constant(222)
add_op = a + b
sess.run(add_op)

333

In [5]:
# 안녕


In [6]:
 # 안녕

In [7]:
import matplotlib.pyplot as plt
import numpy as np
x = np.arange(-20, 20, 0.1)
y = np.sin(x)
plt.plot(x, y)

In [10]:
%matplotlib inline

In [11]:
x

array([-2.00000000e+01, -1.99000000e+01, -1.98000000e+01, -1.97000000e+01,
       -1.96000000e+01, -1.95000000e+01, -1.94000000e+01, -1.93000000e+01,
       -1.92000000e+01, -1.91000000e+01, -1.90000000e+01, -1.89000000e+01,
       -1.88000000e+01, -1.87000000e+01, -1.86000000e+01, -1.85000000e+01,
       -1.84000000e+01, -1.83000000e+01, -1.82000000e+01, -1.81000000e+01,
       -1.80000000e+01, -1.79000000e+01, -1.78000000e+01, -1.77000000e+01,
       -1.76000000e+01, -1.75000000e+01, -1.74000000e+01, -1.73000000e+01,
       -1.72000000e+01, -1.71000000e+01, -1.70000000e+01, -1.69000000e+01,
       -1.68000000e+01, -1.67000000e+01, -1.66000000e+01, -1.65000000e+01,
       -1.64000000e+01, -1.63000000e+01, -1.62000000e+01, -1.61000000e+01,
       -1.60000000e+01, -1.59000000e+01, -1.58000000e+01, -1.57000000e+01,
       -1.56000000e+01, -1.55000000e+01, -1.54000000e+01, -1.53000000e+01,
       -1.52000000e+01, -1.51000000e+01, -1.50000000e+01, -1.49000000e+01,
       -1.48000000e+01, -

In [12]:
a = tf.constant(120, name="a")
b = tf.constant(120, name="b")
v = tf.Variable(0, name="v")
calc_op = a + b
assign_op = tf.assign(v, calc_op)


Instructions for updating:
Colocations handled automatically by placer.


In [13]:
a = tf.constant(120, name="a")
b = tf.constant(120, name="b")
v = tf.Variable(0, name="v")

In [14]:
calc_op = a + b
assign_op = tf.assign(v, calc_op)

In [15]:
sess.run(assign_op)
print(sess.run(v))

240


In [16]:
p = tf.placeholder(tf.int32, [3])       # int32형 3개의 배열 정의, 크기가 None이면 자유!
y = tf.constant(2)
x2_op = p * y
r1 = sess.run(x2_op, feed_dict={ p: [1, 2, 3] })
r2 = sess.run(x2_op, feed_dict={ p: [10, 20, 30] })

In [17]:
print(sess.run(r1, r2))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
print(sess.run(r1), sess.run(r2))

TypeError: Fetch argument array([2, 4, 6], dtype=int32) has invalid type <class 'numpy.ndarray'>, must be a string or Tensor. (Can not convert a ndarray into a Tensor or Operation.)

In [19]:
print(r1)

[2 4 6]


In [20]:
print(r2)

[20 40 60]


In [21]:
r3 = sess.run(x2_op, feed_dict={ p: [[1, 2, 3], [1,2, 3] })

SyntaxError: invalid syntax (<ipython-input-21-e08988d8a551>, line 1)

In [22]:
r3 = sess.run(x2_op, feed_dict={ p: [[1, 2, 3], [1,2, 3]] })

ValueError: Cannot feed value of shape (2, 3) for Tensor 'Placeholder:0', which has shape '(3,)'

In [23]:
aa = tf.constant(20, name="aa")
bb = tf.constant(30, name="bb")
mul_op = aa * bb
sess.run(mul_op)

600

In [24]:
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
